server:
  servlet:
    context-path: ""
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/lims?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    #schema: classpath:sql/schema.sql
    #data: classpath:sql/data.sql
    #initialization-mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
  redis:
    host: redis
    port: 6379
  mail:
    host: smtp.yeah.net
    username: xxxxxx
    password: xxxxxx
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  type-aliases-package: edu.scnu.lims.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
